// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.ondeck.postgresql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Types
import java.time.LocalDateTime
import scala.util.Using

// Venues can be either open or closed
enum Status(val value: String) {
  case OPEN extends Status("op!en")
  case CLOSED extends Status("clo@sed")
}

case class City (
  slug: String,
  name: String
)

// Venues are places where muisc happens
case class Venue (
  id: Int,
  status: Status,
  statuses: Array[Status],
  // This value appears in public URLs
  slug: String,
  name: String,
  city: String,
  spotifyPlaylist: String,
  songkickId: Option[String],
  tags: Array[String],
  createdAt: LocalDateTime
)

