// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.manytypes.postgresql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.UUID
import scala.util.Using

case class ExampleTable (
  id: Int,
  dates: Array[LocalDate],
  timestamps: Array[LocalDateTime],
  uuids: Array[UUID]
)

