// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.booktest.postgresql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Types
import java.time.OffsetDateTime
import scala.util.Using

trait Queries {
  def booksByTags(dollar1: List[String]): List<BooksByTagsRow>
  
  def booksByTitleYear(title: String, year: Int): List<Book>
  
  def createAuthor(name: String): Option[Author]
  
  def createBook(
      authorId: Int,
      isbn: String,
      bookType: BookType,
      title: String,
      year: Int,
      available: OffsetDateTime,
      tags: List[String]): Option[Book]
  
  def deleteBook(bookId: Int): Unit
  
  def getAuthor(authorId: Int): Option[Author]
  
  def getBook(bookId: Int): Option[Book]
  
  def updateBook(
      title: String,
      tags: List[String],
      bookId: Int): Unit
  
  def updateBookISBN(
      title: String,
      tags: List[String],
      isbn: String,
      bookId: Int): Unit
  
}

