// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.booktest.mysql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.time.LocalDateTime
import scala.util.Using

enum BooksBookType(val value: String) {
  case FICTION extends BooksBookType("FICTION")
  case NONFICTION extends BooksBookType("NONFICTION")
}

case class Author (
  authorId: Int,
  name: String
)

case class Book (
  bookId: Int,
  authorId: Int,
  isbn: String,
  bookType: BooksBookType,
  title: String,
  yr: Int,
  available: LocalDateTime,
  tags: String
)

