// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.ondeck.postgresql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Types
import java.time.LocalDateTime
import scala.util.Using

trait Queries {
  def createCity(name: String, slug: String): Option[City]
  
  def createVenue(
      slug: String,
      name: String,
      city: String,
      spotifyPlaylist: String,
      status: Status,
      statuses: List[Status],
      tags: List[String]): Option[Int]
  
  def deleteVenue(slug: String): Unit
  
  def getCity(slug: String): Option[City]
  
  def getVenue(slug: String, city: String): Option[Venue]
  
  def listCities(): List<City>
  
  def listVenues(city: String): List<Venue>
  
  def updateCityName(name: String, slug: String): Unit
  
  def updateVenueName(name: String, slug: String): Option[Int]
  
  def venueCountByCity(): List<VenueCountByCityRow>
  
}

