// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.ondeck.mysql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Timestamp
import java.time.Instant
import scala.util.Using

enum VenueStatus(val value: String) {
  case OPEN extends VenueStatus("open")
  case CLOSED extends VenueStatus("closed")
}

case class City (
  slug: String,
  name: String
)

// Venues are places where muisc happens
case class Venue (
  id: Long,
  // Venues can be either open or closed
  status: VenueStatus,
  statuses: Option[String],
  // This value appears in public URLs
  slug: String,
  name: String,
  city: String,
  spotifyPlaylist: String,
  songkickId: Option[String],
  tags: Option[String],
  createdAt: Instant
)

