// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.ondeck.mysql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Timestamp
import java.time.Instant
import scala.util.Using

val createCitySQL = """-- name: createCity :exec
INSERT INTO city (
    name,
    slug
) VALUES (
    ?,
    ? 
)
"""

val createVenueSQL = """-- name: createVenue :execresult
INSERT INTO venue (
    slug,
    name,
    city,
    created_at,
    spotify_playlist,
    status,
    statuses,
    tags
) VALUES (
    ?,
    ?,
    ?,
    NOW(),
    ?,
    ?,
    ?,
    ?
)
"""

val deleteVenueSQL = """-- name: deleteVenue :exec
DELETE FROM venue
WHERE slug = ? AND slug = ?
"""

val getCitySQL = """-- name: getCity :one
SELECT slug, name
FROM city
WHERE slug = ?
"""

val getVenueSQL = """-- name: getVenue :one
SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE slug = ? AND city = ?
"""

val listCitiesSQL = """-- name: listCities :many
SELECT slug, name
FROM city
ORDER BY name
"""

val listVenuesSQL = """-- name: listVenues :many
SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE city = ?
ORDER BY name
"""

val updateCityNameSQL = """-- name: updateCityName :exec
UPDATE city
SET name = ?
WHERE slug = ?
"""

val updateVenueNameSQL = """-- name: updateVenueName :exec
UPDATE venue
SET name = ?
WHERE slug = ?
"""

val venueCountByCitySQL = """-- name: venueCountByCity :many
SELECT
    city,
    count(*)
FROM venue
GROUP BY 1
ORDER BY 1
"""

case class VenueCountByCityRow (
  city: String,
  count: Long
)

class QueriesImpl(private val conn: Connection) extends Queries {

  override def createCity(name: String, slug: String): Unit = {
    Using.resource(conn.prepareStatement(createCitySQL)) { stmt =>
      stmt.setString(1, name)
          stmt.setString(2, slug)

      stmt.execute()
    }
  }

  override def createVenue(
      slug: String,
      name: String,
      city: String,
      spotifyPlaylist: String,
      status: VenueStatus,
      statuses: Option[String],
      tags: Option[String]): Long = {
    Using.resource(conn.prepareStatement(createVenueSQL, Statement.RETURN_GENERATED_KEYS)) { stmt =>
      stmt.setString(1, slug)
          stmt.setString(2, name)
          stmt.setString(3, city)
          stmt.setString(4, spotifyPlaylist)
          stmt.setString(5, status.value)
          stmt.setString(6, statuses.orNull)
          stmt.setString(7, tags.orNull)

      stmt.execute()

      val results = stmt.getGeneratedKeys
      if (!results.next()) {
          throw SQLException("no generated key returned")
      }
      results.getLong(1)
    }
  }

  override def deleteVenue(slug: String, slug_2: String): Unit = {
    Using.resource(conn.prepareStatement(deleteVenueSQL)) { stmt =>
      stmt.setString(1, slug)
          stmt.setString(2, slug_2)

      stmt.execute()
    }
  }

  override def getCity(slug: String): Option[City] = {
    Using.resource(conn.prepareStatement(getCitySQL)) { stmt =>
      stmt.setString(1, slug)

      val results = stmt.executeQuery()
      Option.when(results.next()) {
        val ret = City(
                results.getString(1),
                results.getString(2)
            )
        if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
        }
        ret
      }
    }
  }

  override def getVenue(slug: String, city: String): Option[Venue] = {
    Using.resource(conn.prepareStatement(getVenueSQL)) { stmt =>
      stmt.setString(1, slug)
          stmt.setString(2, city)

      val results = stmt.executeQuery()
      Option.when(results.next()) {
        val ret = Venue(
                results.getLong(1),
                VenueStatus.valueOf(results.getString(2)),
                Option(results.getObject(3)).map { _ => results.getString(3) },
                results.getString(4),
                results.getString(5),
                results.getString(6),
                results.getString(7),
                Option(results.getObject(8)).map { _ => results.getString(8) },
                Option(results.getObject(9)).map { _ => results.getString(9) },
                results.getTimestamp(10).toInstant()
            )
        if (results.next()) {
          throw SQLException("expected one row in result set, but got many")
        }
        ret
      }
    }
  }

  override def listCities(): List[City] = {
    Using.resource(conn.prepareStatement(listCitiesSQL)) { stmt =>
      
      val results = stmt.executeQuery()
      val ret = scala.collection.mutable.ListBuffer.empty[City]
      while (results.next()) {
          ret += City(
                results.getString(1),
                results.getString(2)
            )
      }
      ret.toList
    }
  }

  override def listVenues(city: String): List[Venue] = {
    Using.resource(conn.prepareStatement(listVenuesSQL)) { stmt =>
      stmt.setString(1, city)

      val results = stmt.executeQuery()
      val ret = scala.collection.mutable.ListBuffer.empty[Venue]
      while (results.next()) {
          ret += Venue(
                results.getLong(1),
                VenueStatus.valueOf(results.getString(2)),
                Option(results.getObject(3)).map { _ => results.getString(3) },
                results.getString(4),
                results.getString(5),
                results.getString(6),
                results.getString(7),
                Option(results.getObject(8)).map { _ => results.getString(8) },
                Option(results.getObject(9)).map { _ => results.getString(9) },
                results.getTimestamp(10).toInstant()
            )
      }
      ret.toList
    }
  }

  override def updateCityName(name: String, slug: String): Unit = {
    Using.resource(conn.prepareStatement(updateCityNameSQL)) { stmt =>
      stmt.setString(1, name)
          stmt.setString(2, slug)

      stmt.execute()
    }
  }

  override def updateVenueName(name: String, slug: String): Unit = {
    Using.resource(conn.prepareStatement(updateVenueNameSQL)) { stmt =>
      stmt.setString(1, name)
          stmt.setString(2, slug)

      stmt.execute()
    }
  }

  override def venueCountByCity(): List[VenueCountByCityRow] = {
    Using.resource(conn.prepareStatement(venueCountByCitySQL)) { stmt =>
      
      val results = stmt.executeQuery()
      val ret = scala.collection.mutable.ListBuffer.empty[VenueCountByCityRow]
      while (results.next()) {
          ret += VenueCountByCityRow(
                results.getString(1),
                results.getLong(2)
            )
      }
      ret.toList
    }
  }

}

