// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.ondeck.mysql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.sql.Timestamp
import java.time.Instant
import scala.util.Using

trait Queries {
  def createCity(name: String, slug: String): Unit
  
  def createVenue(
      slug: String,
      name: String,
      city: String,
      spotifyPlaylist: String,
      status: VenueStatus,
      statuses: Option[String],
      tags: Option[String]): Long
  
  def deleteVenue(slug: String, slug_2: String): Unit
  
  def getCity(slug: String): Option[City]
  
  def getVenue(slug: String, city: String): Option[Venue]
  
  def listCities(): List[City]
  
  def listVenues(city: String): List[Venue]
  
  def updateCityName(name: String, slug: String): Unit
  
  def updateVenueName(name: String, slug: String): Unit
  
  def venueCountByCity(): List[VenueCountByCityRow]
  
}

