// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.jets

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import scala.util.Using

trait Queries {
  def countPilots(): Option[Long]
  
  def deletePilot(id: Int): Unit
  
  def listPilots(): List<Pilot>
  
}

